language: python

jobs:
  include:
    - services: docker
    - os: osx
      language: shell

env:
  global:
    - CIBW_BUILD="cp27-* cp35-* cp36-* cp37-* cp38-*"
    - TWINE_USERNAME=__token__

install:
  - python3 -m pip install cibuildwheel==1.3.0

script:
  - python3 -m cibuildwheel --output-dir wheelhouse

after_success:
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload wheelhouse/*.whl
    fi
