language: python

jobs:
  include:
    - services: docker
    - os: osx
      language: shell
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.0
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"

env:
  global:
    - TWINE_USERNAME=__token__

install:
  - python3 -m pip install cibuildwheel==1.3.0

script:
  - python3 -m cibuildwheel --output-dir wheelhouse

after_success:
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload wheelhouse/*.whl
    fi
